### ISSUE TITLE
configuration: change config file to be a list of values

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/pretty-git-prompt#14]
```yaml
values:
  - type: new
    pre...
    post...
  - type: changed
    ...
  - type: remote
    displ...
    ahead:
      pre...
```
