### ISSUE TITLE
Surround entire git prompt

### ISSUE THREAD

**Issue by rosstimson** [TomasTomecek/pretty-git-prompt#32]
I've recently switch to your tool after being a long time user of [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt).

With zsh-git-prompt I was using the following config in my `~/.zshrc`:

```
PROMPT='${green}%m${reset_color}:%c$(git_super_status) %# '
````
which gave me a prompt like so:

![pretty-git-prompt2](https://user-images.githubusercontent.com/50034/33797497-b97ad39a-dd00-11e7-91f0-c0b06765bef3.png)

As you can see I have the entire git prompt stuff surrounded by parentheses to separate it.

I cannot seem to work out how I can achieve the same with your tool which I have configured with:

```
PROMPT='${green}%m${reset_color}:%c$(pretty-git-prompt) %# '
```

I've also used the example `pretty-git-prompt.yml` from:  https://github.com/TomasTomecek/pretty-git-prompt/blob/master/files/pretty-git-prompt.yml.zsh

This gives me a prompt like:

![pretty-git-prompt1](https://user-images.githubusercontent.com/50034/33797517-593475d0-dd01-11e7-995c-02641d474ee3.png)

Is there a way for me to wrap the whole thing in parentheses without hardcoding them into my prompt config in `~/.zshrc` which of course means I'll see empty parentheses whenever I'm in a non-git directory?

I hope this makes sense, many thanks for your awesome tool.

**Comment by TomasTomecek** [comment]
Hi Ross, thanks for trying out this tool!

It is possible to do what you want -- using `separator`. All you need to do, is to start and end the values list with a separator:

```yaml
values:
    - type: separator
      display: always
      pre_format: '('
      post_format: ''

    - type: repository_state

   ...

    - type: ...

    - type: separator
      display: always
      pre_format: ')'
      post_format: ''
```

`pretty-git-prompt` will not print anything once outside of a git repo. Otherwise it will wrap the output with parentheses. I tried `display: surrounded` and it didn't work, which I think is a bug actually, otherwise `display: always` works just fine.

Let me know if you need any more help!
